# This Dockerfile is for development only. It sets up
# the dependencies, but you will need to actually
# build the package from there.
FROM buildpack-deps:xenial

# Install vim with python enabled
RUN apt-get update && apt-get install -y --no-install-recommends \
    python-dev \
    vim-nox-py2

RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

# Dependencies
RUN pip install --no-cache-dir \
    google-api-python-client \
    Cython \
    py-stackexchange \
    lxml

# Install Vundle
RUN git clone --depth=1 https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim && \
    wget https://raw.githubusercontent.com/VundleVim/Vundle.vim/11fdc428fe741f4f6974624ad76ab7c2b503b73e/test/minirc.vim -O $HOME/.vimrc

WORKDIR /workspace

CMD ["/bin/bash"]
